### ISSUE TITLE
When executing `pip install -r requirements.txt -v`, an error will occur

### ISSUE THREAD

**Issue by zhiwenluo0802** [muehlburger/dx-2024-flex#1]
When executing `pip install -r requirements.txt -v`, an error will occur because the `logging` package is a built-in Python module and does not need to be installed. It is recommended to remove this package from the `requirements.txt` file.

**Comment by muehlburger** [comment]
Thank's for the hint. The updated version will be comitted soon.

**Comment by muehlburger** [comment]
https://github.com/muehlburger/dx-2024-flex/commit/8521a7cac675af8583f573389bab267f639d6158 should fix this issue. Thank's for reporting!
